# Generated by Django 3.1.3 on 2021-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria1_kerjasama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lembaga_mitra', models.CharField(max_length=100)),
                ('tingkat', models.CharField(choices=[('I', 'Internasional'), ('N', 'Nasional'), ('L', 'Lokal')], max_length=2)),
                ('judul_kegiatan', models.CharField(max_length=200)),
                ('waktu', models.DateField()),
                ('durasi', models.CharField(max_length=10)),
                ('bukti', models.CharField(max_length=100)),
                ('tahun_berakhirnya', models.DateField()),
            ],
            options={
                'verbose_name': 'Kriteria-1 Kerjasama',
                'verbose_name_plural': 'Kriteria-1 Kerjasama',
            },
        ),
    ]
