# Generated by Django 3.1.3 on 2021-08-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kriteria1_kerjasama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria2_Seleksimahasiswabaru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('daya_tampung', models.CharField(max_length=10)),
                ('jumlah_calon_pendaftar', models.IntegerField(verbose_name='Jumlah Pendaftar Calon Mahasiswa')),
                ('jumlah_calon_lulus', models.IntegerField(verbose_name='Jumlah Lulus Seleksi Calon Mahasiswa')),
                ('jumlah_baru_reguler', models.IntegerField(verbose_name='Jumlah Mahasiswa Baru Reguler')),
                ('jumlah_baru_transfer', models.IntegerField(verbose_name='Jumlah Mahasiswa Baru Transfer')),
                ('jumlah_aktif_reguler', models.IntegerField(verbose_name='Jumlah Mahasiswa Aktif Baru')),
                ('jumlah_aktif_transfer', models.IntegerField(verbose_name='Jumlah Mahasiswa Aktif Transfer')),
            ],
            options={
                'verbose_name': 'Kriteria-2 Seleksi Mahasiswa Baru',
                'verbose_name_plural': 'Kriteria-2 Seleksi Mahasiswa Baru',
            },
        ),
        migrations.CreateModel(
            name='Kriteria2_Mahasiswaasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_aktif_ts0', models.IntegerField()),
                ('jumlah_aktif_ts1', models.IntegerField()),
                ('jumlah_aktif_ts2', models.IntegerField()),
                ('jumlah_asing_penuh_ts0', models.IntegerField()),
                ('jumlah_asing_penuh_ts1', models.IntegerField()),
                ('jumlah_asing_penuh_ts2', models.IntegerField()),
                ('jumlah_asing_paruh_ts0', models.IntegerField()),
                ('jumlah_asing_paruh_ts1', models.IntegerField()),
                ('jumlah_asing_paruh_ts2', models.IntegerField()),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program_studi')),
            ],
            options={
                'verbose_name': 'Kriteria-2 Mahasiswa Asing',
                'verbose_name_plural': 'Kriteria-2 Mahasiswa Asing',
            },
        ),
    ]
