# Generated by Django 3.1.3 on 2021-08-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kriteria2_mahasiswaasing_kriteria2_seleksimahasiswabaru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria2_mahasiswaasing',
            name='program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.program_studi'),
        ),
    ]
